-- 청약홈 호출 제한, 공개 스냅샷 이력, 문서 동기화의 실제 완료 상태를 영구 보존한다.
create table if not exists public.notice_upstream_state (
  source_key text primary key,
  retry_after timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

alter table public.notice_upstream_state enable row level security;
comment on table public.notice_upstream_state is 'service role only upstream quota and retry state';

create table if not exists public.notice_public_snapshot_history (
  id bigint generated by default as identity primary key,
  feed_key text not null,
  notices jsonb not null,
  stats jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint notice_public_snapshot_history_notices_array check (jsonb_typeof(notices) = 'array')
);

alter table public.notice_public_snapshot_history enable row level security;
comment on table public.notice_public_snapshot_history is 'service role only immutable validated feed history';
create index if not exists notice_public_snapshot_history_feed_verified_idx
  on public.notice_public_snapshot_history (feed_key, verified_at desc);

create table if not exists public.notice_sync_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  status text not null check (status in ('succeeded', 'failed')),
  started_at timestamptz not null,
  finished_at timestamptz not null,
  result jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now()
);

alter table public.notice_sync_runs enable row level security;
comment on table public.notice_sync_runs is 'service role only semantic scheduled sync results';
create index if not exists notice_sync_runs_job_started_idx
  on public.notice_sync_runs (job_name, started_at desc);

-- 이 테이블들은 Edge 서비스 역할만 사용한다. RLS에만 기대지 않고 공개 역할 권한도 제거한다.
revoke all on table public.notice_model_cache from anon, authenticated;
revoke all on table public.notice_location_cache from anon, authenticated;
revoke all on table public.notice_public_snapshots from anon, authenticated;
revoke all on table public.notice_document_cache from anon, authenticated;
revoke all on table public.notice_collection_conflicts from anon, authenticated;
revoke all on table public.notice_sync_auth from anon, authenticated;
revoke all on table public.notice_upstream_state from anon, authenticated;
revoke all on table public.notice_public_snapshot_history from anon, authenticated;
revoke all on table public.notice_sync_runs from anon, authenticated;
revoke all on sequence public.notice_public_snapshot_history_id_seq from anon, authenticated;
revoke all on sequence public.notice_sync_runs_id_seq from anon, authenticated;

-- 고객 GET은 영구 스냅샷만 읽고, 업스트림 갱신은 인증된 시간별 작업만 수행한다.
do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id from cron.job where jobname = 'homebom-notices-refresh';
  if existing_job_id is not null then perform cron.unschedule(existing_job_id); end if;
end $$;

select cron.schedule(
  'homebom-notices-refresh',
  '5 * * * *',
  $schedule$
  select net.http_post(
    url := 'https://neqjmxaneibobpedgsnl.supabase.co/functions/v1/notices?refresh=1',
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-sync-token', coalesce((
        select decrypted_secret
        from vault.decrypted_secrets
        where name = 'homebom_notice_sync_token'
        limit 1
      ), '')
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  );
  $schedule$
);

-- 이력은 롤백·장애 분석에 충분한 30일만 보존한다.
do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id from cron.job where jobname = 'homebom-snapshot-history-retention';
  if existing_job_id is not null then perform cron.unschedule(existing_job_id); end if;
end $$;

select cron.schedule(
  'homebom-snapshot-history-retention',
  '40 3 * * *',
  $$delete from public.notice_public_snapshot_history where created_at < now() - interval '30 days'$$
);
