-- 검증된 공개 피드를 Edge 인스턴스와 독립적으로 보존한다.
create table if not exists public.notice_public_snapshots (
  feed_key text primary key,
  notices jsonb not null,
  stats jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null,
  source_versions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notice_public_snapshots_array check (jsonb_typeof(notices) = 'array')
);

alter table public.notice_public_snapshots enable row level security;
comment on table public.notice_public_snapshots is 'service role only last-known-good validated public notice feed';

-- 공식 상세 HTML·PDF의 변경 감지와 결정론적 추출 결과를 보존한다.
create table if not exists public.notice_document_cache (
  notice_key text primary key,
  notice_url text,
  document_url text,
  source_type text not null check (source_type in ('notice-html', 'notice-pdf', 'official-page', 'public-agency')),
  etag text,
  last_modified text,
  document_hash text,
  revision text,
  parsed_fields jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  conflicts jsonb not null default '[]'::jsonb,
  status text not null check (status in ('verified', 'single-official-source', 'conflict', 'not-provided', 'retrying')),
  fetched_at timestamptz not null,
  retry_after timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  constraint notice_document_cache_fields_object check (jsonb_typeof(parsed_fields) = 'object'),
  constraint notice_document_cache_provenance_object check (jsonb_typeof(provenance) = 'object'),
  constraint notice_document_cache_conflicts_array check (jsonb_typeof(conflicts) = 'array')
);

alter table public.notice_document_cache enable row level security;
comment on table public.notice_document_cache is 'service role only official notice HTML and PDF extraction cache';
create index if not exists notice_document_cache_retry_after_idx
  on public.notice_document_cache (retry_after);

-- 공식 출처가 서로 다를 때 임의 선택하지 않고 필드 단위로 기록한다.
create table if not exists public.notice_collection_conflicts (
  id bigint generated by default as identity primary key,
  notice_key text not null,
  field_name text not null,
  candidates jsonb not null,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolution jsonb,
  constraint notice_collection_conflicts_candidates_array check (jsonb_typeof(candidates) = 'array')
);

alter table public.notice_collection_conflicts enable row level security;
comment on table public.notice_collection_conflicts is 'service role only unresolved official-source field conflicts';
create index if not exists notice_collection_conflicts_open_idx
  on public.notice_collection_conflicts (notice_key, field_name)
  where resolved_at is null;

-- 예약 함수 토큰은 Vault에 원문, 서비스 전용 테이블에 SHA-256만 보관한다.
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.notice_sync_auth (
  singleton boolean primary key default true check (singleton),
  token_hash text not null check (length(token_hash) = 64),
  rotated_at timestamptz not null default now()
);

alter table public.notice_sync_auth enable row level security;
comment on table public.notice_sync_auth is 'service role only hash for scheduled official document sync authentication';

do $$
declare
  sync_token text := encode(extensions.gen_random_bytes(32), 'hex');
  existing_secret_id uuid;
begin
  select id into existing_secret_id
  from vault.secrets
  where name = 'homebom_notice_sync_token'
  limit 1;

  if existing_secret_id is null then
    perform vault.create_secret(sync_token, 'homebom_notice_sync_token', 'HomeBom official document sync token');
  else
    perform vault.update_secret(existing_secret_id, sync_token, 'homebom_notice_sync_token', 'HomeBom official document sync token');
  end if;

  insert into public.notice_sync_auth (singleton, token_hash, rotated_at)
  values (true, encode(extensions.digest(sync_token, 'sha256'), 'hex'), now())
  on conflict (singleton) do update
  set token_hash = excluded.token_hash,
      rotated_at = excluded.rotated_at;
end $$;

-- 2시간마다 공식 문서를 동기화한다.
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id from cron.job where jobname = 'homebom-official-document-sync';
  if existing_job_id is not null then perform cron.unschedule(existing_job_id); end if;
end $$;

select cron.schedule(
  'homebom-official-document-sync',
  '17 */2 * * *',
  $schedule$
  select net.http_post(
    url := 'https://neqjmxaneibobpedgsnl.supabase.co/functions/v1/sync-notice-documents',
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-sync-token', coalesce((
        select decrypted_secret
        from vault.decrypted_secrets
        where name = 'homebom_notice_sync_token'
        limit 1
      ), '')
    ),
    body := '{}'::jsonb
  );
  $schedule$
);
